# Generated by Django 2.1 on 2018-08-30 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beans',
            fields=[
                ('beans_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('roaster', models.CharField(max_length=30)),
                ('date_purchased', models.DateField()),
                ('date_roasted', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('brew_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mass_beans', models.PositiveSmallIntegerField()),
                ('mass_water', models.PositiveSmallIntegerField()),
                ('brew_time', models.DurationField()),
                ('comments', models.CharField(max_length=200)),
                ('review', models.CharField(choices=[('AW', 'Awful'), ('BD', 'Bad'), ('OK', 'Ok'), ('GD', 'Good'), ('AG', 'Amazing')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beans_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewreview.Beans')),
            ],
        ),
        migrations.CreateModel(
            name='Equitment',
            fields=[
                ('equitment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('e_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='equitment_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewreview.Equitment'),
        ),
        migrations.AddField(
            model_name='brew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
