# Generated by Django 2.1 on 2018-08-30 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
