# Generated by Django 2.1.4 on 2018-12-06 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('contacts.contact',),
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='title',
        ),
    ]
