# Generated by Django 2.1.1 on 2018-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('section_h', 'home'), ('section_p', 'proyectos'), ('section_e', 'eventos'), ('section_m', 'miembros')], default='proyectos', max_length=24),
        ),
    ]
