# Generated by Django 2.1.1 on 2018-09-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0002_auto_20180831_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_es', models.CharField(max_length=256)),
                ('evento_en', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_es', models.TextField(blank=True)),
                ('texto_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('intro_es', models.TextField()),
                ('intro_en', models.TextField()),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
