# Generated by Django 2.1.1 on 2018-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0003_auto_20180904_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('role_dir', 'directora'), ('role_inv', 'investigadores'), ('role_doc', 'doctorandos'), ('role_phd', 'phpthesis'), ('role_col', 'colaboradores')], max_length=24)),
            ],
        ),
    ]
