# Generated by Django 2.1.1 on 2018-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='aux',
            field=models.CharField(default='Null', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('role_dir', 'directora'), ('role_inv', 'investigadores'), ('role_doc', 'doctorandos'), ('role_phd', 'phpthesis'), ('role_col', 'colaboradores')], default='role_inv', max_length=24),
        ),
    ]
