# Generated by Django 2.1.1 on 2018-09-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0005_auto_20180904_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='aux',
        ),
    ]
