# Generated by Django 2.1.1 on 2018-09-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0006_remove_role_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lcai.Role')),
                ('nombre', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('lcai.role',),
        ),
    ]
