# Generated by Django 2.1.1 on 2018-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcai', '0007_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='descrip_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='descrip_es',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='enlace_a_web',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='enlace_a_web_personal',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='universidad_en',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='universidad_es',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('role_dir', 'Directora'), ('role_inv', 'Investigadores'), ('role_doc', 'Doctorandos'), ('role_phd', 'Phd / Thesis'), ('role_col', 'Colaboradores')], default='role_inv', max_length=24),
        ),
    ]
