# Generated by Django 2.1 on 2018-08-27 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('composer_last_name', models.CharField(max_length=200)),
                ('composer_first_name', models.CharField(max_length=200)),
                ('editor_last_name', models.CharField(max_length=200)),
                ('editor_first_name', models.CharField(max_length=200)),
                ('instrumentation', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
