# Generated by Django 2.1 on 2018-08-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180828_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='music',
            name='last_modified',
        ),
    ]
