# Generated by Django 2.1 on 2018-08-28 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180828_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['composer_last_name', 'title'], 'verbose_name': 'music', 'verbose_name_plural': 'music'},
        ),
        migrations.AddField(
            model_name='music',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
