# Generated by Django 2.1 on 2018-08-28 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_music_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
