# Generated by Django 2.1 on 2018-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180828_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
