# Generated by Django 2.1.2 on 2018-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('city_state', models.CharField(max_length=200)),
                ('date_found', models.DateField(auto_now_add=True)),
                ('date_applied', models.DateField(blank=True)),
            ],
        ),
    ]
