# Generated by Django 2.1.2 on 2018-10-22 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('city_state', models.CharField(max_length=200)),
                ('date_found', models.DateField(auto_now_add=True)),
                ('date_applied', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
