# Generated by Django 2.1.2 on 2018-10-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181022_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_found',
        ),
    ]
