# Generated by Django 2.1.2 on 2018-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_personaljob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
