# Generated by Django 2.1.4 on 2018-12-07 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20181207_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='isd',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalnote',
            name='note_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users_app.Note'),
        ),
    ]
