# Generated by Django 2.1.3 on 2018-12-06 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20181204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
