# Generated by Django 2.1.2 on 2018-10-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='concept',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='language',
        ),
    ]
