# Generated by Django 2.1.2 on 2018-10-25 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpilepsyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('numOfDiagnoses', models.IntegerField(max_length=20)),
            ],
        ),
    ]
