# Generated by Django 2.1.2 on 2018-10-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epilepsy', '0002_auto_20181025_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEpilepsyData',
            fields=[
                ('epilepsydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='epilepsy.EpilepsyData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('epilepsy.epilepsydata',),
        ),
    ]
