# Generated by Django 2.1.2 on 2018-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy', '0003_personalepilepsydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilepsydata',
            name='numOfDiagnoses',
            field=models.IntegerField(),
        ),
    ]
