# Generated by Django 2.1.2 on 2018-10-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrigItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
