# Generated by Django 2.1.2 on 2018-10-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrigItems', '0006_fruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('fruit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Groceries',
            new_name='Grocery',
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
    ]
