# Generated by Django 2.1.2 on 2018-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrigItems', '0007_auto_20181023_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='fruit',
            new_name='fruit_name',
        ),
        migrations.AddField(
            model_name='fruit',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
