# Generated by Django 2.1.4 on 2018-12-07 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('was_enjoyed', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
