# Generated by Django 2.1.2 on 2018-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20181023_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(default='', max_length=1),
        ),
    ]
