# Generated by Django 2.1.2 on 2018-10-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20181023_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='First', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Last', max_length=50),
        ),
    ]
