# Generated by Django 2.1.2 on 2018-10-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20181023_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
