# Generated by Django 2.1.2 on 2018-10-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20181023_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='blood_type',
        ),
    ]
