# Generated by Django 2.1.2 on 2018-10-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
