# Generated by Django 2.1.2 on 2018-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0004_releases'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='RottenTomatoes',
            field=models.URLField(blank=True),
        ),
    ]
