# Generated by Django 2.1.2 on 2018-10-23 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0006_auto_20181023_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Releases',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
