# Generated by Django 2.1.2 on 2018-10-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0007_auto_20181023_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
