# Generated by Django 2.1.2 on 2018-10-24 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0010_auto_20181024_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='movies_ptr',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
