# Generated by Django 2.1.2 on 2018-10-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horror_movies', '0011_auto_20181024_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
    ]
