# Generated by Django 2.1.2 on 2018-10-24 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horror_movies', '0012_remove_announcement_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMovie',
            fields=[
                ('movies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='horror_movies.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('horror_movies.movies',),
        ),
    ]
