# Generated by Django 2.1.2 on 2018-10-23 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('shares_outstanding', models.DecimalField(decimal_places=0, max_digits=100000000000)),
            ],
        ),
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_prices.Companies')),
            ],
        ),
    ]
