# Generated by Django 2.1.2 on 2018-10-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_prices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewClass',
        ),
    ]
