# Generated by Django 2.1.2 on 2018-10-22 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Phone', models.IntegerField()),
                ('Website', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('Zip', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
