# Generated by Django 2.1 on 2018-08-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Thingy',
        ),
    ]
