# Generated by Django 2.1 on 2018-08-28 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thingies', '0002_auto_20180827_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thingy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
