# Generated by Django 2.1.2 on 2018-10-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0003_auto_20181023_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_nodified',
            new_name='last_modified',
        ),
    ]
