# Generated by Django 2.1.2 on 2018-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_book_pages1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages1',
        ),
    ]
