# Generated by Django 2.1.2 on 2018-10-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0007_personalbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
