# Generated by Django 2.1.2 on 2018-10-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0008_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
