# Generated by Django 2.1.2 on 2018-10-22 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencydata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('the_open', models.FloatField()),
                ('the_high', models.FloatField()),
                ('the_low', models.FloatField()),
                ('the_close', models.FloatField()),
                ('bar_type', models.CharField(max_length=7)),
            ],
        ),
    ]
