# Generated by Django 2.1.2 on 2018-10-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
