# Generated by Django 2.1.2 on 2018-10-23 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencydata', '0002_auto_20181022_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='currencydata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
