# Generated by Django 2.1.2 on 2018-10-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whiskey',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
