# Generated by Django 2.1.2 on 2018-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeyapp', '0003_personalwhiskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwhiskey',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
