# Generated by Django 2.1.1 on 2018-09-04 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprintStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sprint Status',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('current_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('student_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_sprints', models.PositiveSmallIntegerField()),
                ('passed_sprints', models.PositiveSmallIntegerField()),
                ('sprint_pass_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProjectManager')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_self_rating', models.PositiveSmallIntegerField()),
                ('what_went_well', models.TextField(blank=True)),
                ('what_could_have_gone_better', models.TextField(blank=True)),
                ('review_rating', models.PositiveSmallIntegerField()),
                ('review_great', models.TextField(blank=True)),
                ('requested_improvements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sprint')),
                ('sprint_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SprintStatus')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Student')),
            ],
        ),
    ]
