# Generated by Django 2.1 on 2018-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_studentreport_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='review_great',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='review_rating',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
