# Generated by Django 2.1.1 on 2018-09-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreport',
            name='sprint_pass_rate',
        ),
    ]
