# Generated by Django 2.1.1 on 2018-09-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_studentreport_sprint_pass_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='dashboard.Student'),
        ),
    ]
