# Generated by Django 2.1 on 2018-08-29 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180828_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('project_manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_manager_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SprintStatus',
            fields=[
                ('sprint_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprint_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('current_section', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='sprint_status',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='student_name',
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprint_status_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SprintStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreport',
            name='project_manager_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProjectManager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreport',
            name='student_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Student'),
            preserve_default=False,
        ),
    ]
