# Generated by Django 2.1 on 2018-08-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180830_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='id',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section_name',
        ),
    ]
