# Generated by Django 2.1.1 on 2018-09-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180906_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreport',
            old_name='student_id',
            new_name='student',
        ),
    ]
