# Generated by Django 2.1.1 on 2018-09-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180906_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreport',
            old_name='project_manager_id',
            new_name='project_manager',
        ),
    ]
