# Generated by Django 2.1 on 2018-08-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180830_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='last_updated',
            new_name='last_modified',
        ),
    ]
