# Generated by Django 2.1 on 2018-08-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180830_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('section_name',)},
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Section'),
        ),
    ]
