# Generated by Django 2.1 on 2018-08-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180830_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='project_manager_name',
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='project_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Student'),
        ),
    ]
