# Generated by Django 2.1 on 2018-08-30 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180830_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='project_manager_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='project_manager_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
