# Generated by Django 2.1.2 on 2018-10-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodJournal', '0002_auto_20181023_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='Note',
        ),
    ]
