# Generated by Django 2.1.2 on 2018-10-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgup',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='imgup',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
