# Generated by Django 2.1.2 on 2018-10-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img_up', '0002_auto_20181023_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epilepsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('numOfTotalCases', models.IntegerField()),
                ('numOfChildCases', models.IntegerField()),
                ('numOfAdultCases', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImgUp',
        ),
        migrations.CreateModel(
            name='EpilepsyUserInput',
            fields=[
                ('epilepsy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='img_up.Epilepsy')),
                ('user_name', models.CharField(max_length=30)),
            ],
            bases=('img_up.epilepsy',),
        ),
    ]
