# Generated by Django 2.1.2 on 2018-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
