# Generated by Django 2.1.2 on 2018-10-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
