# Generated by Django 2.1.2 on 2018-10-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenline', '0003_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='email', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
