# Generated by Django 2.1 on 2018-08-28 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=200)),
                ('blog_post', models.TextField(blank=True)),
            ],
        ),
    ]
