# Generated by Django 2.1.3 on 2018-11-07 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
