# Generated by Django 2.1.3 on 2018-11-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
