# Generated by Django 2.1.4 on 2018-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
