# Generated by Django 2.1.4 on 2018-12-05 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField()),
                ('choices', models.CharField(max_length=50, verbose_name=(('steal', 's'), ('beg', 'b'), ('launder', 'l'), ('borrow', 'bo')))),
                ('amount', models.IntegerField(default=1000)),
            ],
        ),
    ]
