# Generated by Django 2.1.2 on 2018-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='T_or_F',
            field=models.BooleanField(blank=True),
        ),
    ]
