# Generated by Django 2.1.4 on 2018-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181203_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
