# Generated by Django 2.1.1 on 2018-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
