# Generated by Django 2.1.1 on 2018-09-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='last_modified',
        ),
    ]
