# Generated by Django 2.1 on 2018-08-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180827_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Note',
        ),
    ]
