# Generated by Django 2.1.4 on 2018-12-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181207_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalNote',
        ),
    ]
