# Generated by Django 2.1.1 on 2018-09-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180917_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='still_touring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='type_of_music',
            field=models.CharField(choices=[('RO', 'Rock'), ('JA', 'Jazz'), ('FU', 'Funk'), ('CO', 'Country')], default='RO', max_length=2),
        ),
    ]
