# Generated by Django 2.1.1 on 2018-09-17 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180917_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(default='http://www.imdb.com'),
        ),
        migrations.AddField(
            model_name='movie',
            name='on_dvd',
            field=models.BooleanField(default=True),
        ),
    ]
