# Generated by Django 2.1.4 on 2018-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181203_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
