# Generated by Django 2.1.4 on 2018-12-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompsciNotes',
            fields=[
                ('notes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Notes')),
                ('title2', models.CharField(max_length=200)),
                ('content2', models.TextField(blank=True)),
            ],
            bases=('notes.notes',),
        ),
    ]
