# Generated by Django 2.1.1 on 2018-09-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180917_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='pertinent_website',
            field=models.URLField(default='https://www.rockarchive.com/artists'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_tag',
            field=models.CharField(choices=[('TD', 'To-Do'), ('WS', 'Words of Wisdom'), ('NS', 'Nonsense')], default='NS', max_length=2),
        ),
    ]
