# Generated by Django 2.1.2 on 2018-10-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
    ]
