# Generated by Django 2.1.4 on 2018-12-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_personalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretNote',
            fields=[
                ('personalnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.PersonalNote')),
                ('very_secretive', models.BooleanField()),
            ],
            bases=('notes.personalnote',),
        ),
    ]
