# Generated by Django 2.1.1 on 2018-09-18 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180918_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 4, 54, 27, 629240, tzinfo=utc)),
        ),
    ]
