# Generated by Django 2.1.1 on 2018-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_tag_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='note_id',
            field=models.IntegerField(default=1),
        ),
    ]
