# Generated by Django 2.1.1 on 2018-09-18 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180917_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 17, 8, 39, 379936, tzinfo=utc), editable=False),
        ),
    ]
