# Generated by Django 2.1.1 on 2018-09-18 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180918_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 22, 30, 0, 65116, tzinfo=utc), editable=False),
        ),
    ]
