# Generated by Django 2.1.1 on 2018-09-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180918_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.CharField(choices=[('admin', 'admin'), ('paid_user', 'customer'), ('free_user', 'prospect')], default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
