# Generated by Django 2.1.3 on 2018-11-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_personalnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
