# Generated by Django 2.1.1 on 2018-09-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_customuser_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalnote',
            old_name='user',
            new_name='custom_user',
        ),
    ]
