# Generated by Django 2.1.1 on 2018-09-17 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_auto_20180917_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notes.note',),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_tag',
            field=models.CharField(choices=[('TD', 'To-Do'), ('WS', 'Words of Wisdom'), ('NS', 'Nonsense')], default='NS', max_length=2),
        ),
    ]
