# Generated by Django 2.1.4 on 2018-12-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20181203_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default='2018-12-03T23:20:06.003025'),
        ),
    ]
