# Generated by Django 2.1.1 on 2018-09-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_beer_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Brewery'),
        ),
    ]
