# Generated by Django 2.1.1 on 2018-09-19 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180919_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 22, 17, 3, 807697, tzinfo=utc), editable=False),
        ),
    ]
