# Generated by Django 2.1.3 on 2018-11-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20181114_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='note',
            name='completed',
        ),
    ]
