# Generated by Django 2.1.1 on 2018-09-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_beer_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
