# Generated by Django 2.1.1 on 2018-09-20 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180919_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 22, 29, 19, 531086, tzinfo=utc), editable=False),
        ),
    ]
