# Generated by Django 2.1.3 on 2018-11-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_author_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
