# Generated by Django 2.1.1 on 2018-09-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20180917_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='modified_at',
            new_name='last_modified',
        ),
    ]
