# Generated by Django 2.1.1 on 2018-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20180917_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='note_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
