# Generated by Django 2.1.3 on 2018-11-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20181114_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
