# Generated by Django 2.1.1 on 2018-09-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_personalnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='note_id',
        ),
    ]
