# Generated by Django 2.1.1 on 2018-09-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_remove_tag_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='note_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
    ]
