# Generated by Django 2.1.1 on 2018-09-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
