# Generated by Django 2.1.1 on 2018-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180917_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.DateField(),
        ),
    ]
