# Generated by Django 2.1.1 on 2018-09-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_personalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrate',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Book')),
                ('illustrated', models.BooleanField()),
            ],
            bases=('notes.book',),
        ),
    ]
