# Generated by Django 2.1.1 on 2018-09-18 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_remove_book_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
