# Generated by Django 2.1.2 on 2018-10-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catsdirectory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='title',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='content',
            new_name='facts',
        ),
    ]
