# Generated by Django 2.1.2 on 2018-10-24 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catsdirectory', '0002_auto_20181023_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
