# Generated by Django 2.1.2 on 2018-10-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catsdirectory', '0003_auto_20181024_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCat',
            fields=[
                ('cat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catsdirectory.Cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('catsdirectory.cat',),
        ),
    ]
