# Generated by Django 2.1.1 on 2018-09-04 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
