# Generated by Django 2.1 on 2018-08-27 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 20, 2, 52, 634069)),
        ),
    ]
