# Generated by Django 2.1 on 2018-08-28 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20180828_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 16, 52, 24, 142622)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 16, 52, 24, 141857)),
        ),
    ]
