# Generated by Django 2.1.2 on 2018-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist', '0003_personalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plan_board',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True),
        ),
    ]
