# Generated by Django 2.1.3 on 2018-12-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='titel',
            new_name='title',
        ),
    ]
