# Generated by Django 2.1.4 on 2018-12-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smurfs', '0003_auto_20181205_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smurf',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='age in years'),
        ),
        migrations.AlterField(
            model_name='smurf',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='hieght in inches'),
        ),
    ]
