# Generated by Django 2.1.4 on 2018-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smurfs', '0004_auto_20181205_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smurf',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='height in inches'),
        ),
    ]
