# Generated by Django 2.1.4 on 2018-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smurfs', '0005_auto_20181205_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smurf',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
