from django.db import models
from uuid import uuid4

# Create your models here.
# id is randomly generated by UUID
# https://en.wikipedia.org/wiki/Universally_unique_identifier
# Primary key is how the database tracks records.
# Default calls a function to randomly generate a unique identifier.
# We make editable false because we never want to change the key.
# Put it at the top of the list of fields because it’s sort of like the index for the record.

class Note(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)

