# Generated by Django 2.1.2 on 2018-10-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
