# Generated by Django 2.1.2 on 2018-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181025_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='primary',
            field=models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'POISON'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='region',
            field=models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'POISON'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='secondary',
            field=models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('ELE', 'Electric'), ('GRA', 'Grass'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'POISON'), ('GRO', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('ROC', 'Rock'), ('GHO', 'Ghost'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=20),
        ),
    ]
