# Generated by Django 2.1.2 on 2018-10-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20181023_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(default='', max_length=2),
        ),
    ]
