# Generated by Django 2.1.2 on 2018-10-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcyclopedia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
