# Generated by Django 2.1.2 on 2018-10-24 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxcyclopedia_app', '0002_entries_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
