# Generated by Django 2.1.2 on 2018-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_personalplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
