# Generated by Django 2.1.2 on 2018-10-22 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesapp.Note')),
            ],
        ),
    ]
