# Generated by Django 2.1.2 on 2018-10-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_auto_20181023_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='thoughts',
            field=models.TextField(blank=True),
        ),
    ]
