# Generated by Django 2.1.2 on 2018-10-25 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_personalnote_private_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='note_ptr',
        ),
        migrations.AddField(
            model_name='personalnote',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
