# Generated by Django 2.1.2 on 2018-10-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_personalnote_private_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
