# Generated by Django 2.1.2 on 2018-10-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0007_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='tags',
        ),
    ]
