# Generated by Django 2.1.2 on 2018-10-23 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181022_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1900)]),
            preserve_default=False,
        ),
    ]
