# Generated by Django 2.1.2 on 2018-10-24 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_djangoist_clothes', '0002_garment_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGarment',
            fields=[
                ('garment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_djangoist_clothes.Garment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('the_djangoist_clothes.garment',),
        ),
    ]
