# Generated by Django 2.1 on 2018-08-28 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cost', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=32)),
                ('cmc', models.IntegerField()),
                ('cardType', models.CharField(max_length=128)),
                ('subType', models.CharField(max_length=32)),
                ('cardSet', models.CharField(max_length=128)),
                ('text', models.TextField()),
            ],
        ),
    ]
