# Generated by Django 2.1 on 2018-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardType',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='colorless', max_length=32),
        ),
    ]
