# Generated by Django 2.1 on 2018-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_added_UserCollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardType',
            field=models.CharField(choices=[('sorcery', 'sorcery'), ('instant', 'instant'), ('land', 'land'), ('creature', 'creature')], max_length=128),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('W', 'white'), ('B', 'black'), ('R', 'red'), ('G', 'green'), ('U', 'blue')], max_length=32),
        ),
    ]
