# Generated by Django 2.1.3 on 2018-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(default='Hardcover Book', max_length=50),
        ),
    ]
