# Generated by Django 2.1 on 2018-08-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheet_Music',
            new_name='SheetMusic',
        ),
    ]
