# Generated by Django 2.1.1 on 2018-09-17 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_usermove'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMove',
            new_name='UserMovie',
        ),
    ]
