# Generated by Django 2.1.1 on 2018-09-18 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.TextField(choices=[('CS', 'Computer Scientist'), ('FS', 'Full Stack Web Developer'), ('DS', 'Data Scientist'), ('RE', 'React Engineer')], max_length=1)),
            ],
        ),
    ]
