# Generated by Django 2.1 on 2018-08-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='updated_on',
            new_name='last_updated',
        ),
    ]
