# Generated by Django 2.1.2 on 2018-10-24 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notNotes', '0003_auto_20181023_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNotNote',
            fields=[
                ('notnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notNotes.NotNote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notNotes.notnote',),
        ),
    ]
