# Generated by Django 2.1.2 on 2018-10-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notNotes', '0005_auto_20181024_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='notnote',
            name='extraContent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notnote',
            name='subtitle',
            field=models.CharField(default='default subtitle', max_length=200),
        ),
    ]
