# Generated by Django 2.1.2 on 2018-10-23 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydb', '0003_auto_20181023_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterDog',
            fields=[
                ('dog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydb.Dog')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mydb.dog',),
        ),
    ]
