# Generated by Django 2.1.4 on 2018-12-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='Quote',
            new_name='quote',
        ),
    ]
