# Generated by Django 2.1 on 2018-08-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'music', 'verbose_name_plural': 'music'},
        ),
        migrations.RenameField(
            model_name='music',
            old_name='created_on',
            new_name='create_at',
        ),
    ]
