# Generated by Django 2.1 on 2018-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180828_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='create_at',
            new_name='created_on',
        ),
    ]
