# Generated by Django 2.1 on 2018-08-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_personalmusic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmusic',
            options={'ordering': ['composer_last_name', 'title'], 'verbose_name': 'personal music', 'verbose_name_plural': 'personal music'},
        ),
    ]
